# TODO: Turn on sun when we're _actually_ working in the office
# TODO: Turn off kitchen white light when Apple TV is playing
# TODO: Notify when window is open when we're not home

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

# device_tracker:
#   - platform: nmap_tracker
#     # Only scan AT HOME phones every X minutes
#     home_interval: 1
#     # Wait X seconds before marking an undetected phone as AWAY
#     consider_home: 180
#     hosts:
#       - 192.168.1.187 # Artem's phone
#       - 192.168.1.195 # Margarita's phone

light:
  - platform: group
    unique_id: group_galaxy
    name: Galaxy
    entities:
      - light.candle
      - light.sausage
      - light.pickle
  - platform: group
    unique_id: group_twix
    name: Twix
    entities:
      - light.hue_bar_left
      - light.hue_bar_right
  - platform: group
    unique_id: group_moon
    name: Moon
    entities:
      - light.moon_1
      - light.moon_2
      - light.moon_3
  - platform: group
    unique_id: group_sun
    name: Sun
    entities:
      - light.sun_1
      - light.sun_2
      - light.sun_3
      - light.sun_4
      - light.sun_5
  - platform: group
    unique_id: group_office_ceiling_lights
    name: Office ceiling lights
    entities:
      - light.sun_1
      - light.sun_2
      - light.sun_3
      - light.sun_4
      - light.sun_5
  - platform: group
    unique_id: group_ambient_lights
    name: Ambient lights
    entities:
      - light.avocado
      - light.luxo
      - light.pizza
      - light.taquito
      - light.hue_bar_left
      - light.hue_bar_right
  - platform: group
    unique_id: group_office_ambient_lights
    name: Office ambient lights
    entities:
      - light.avocado
      - light.luxo
  - platform: group
    unique_id: group_all_lights
    name: All lights
    entities:
      - light.avocado
      - light.luxo
      - light.pizza
      - light.candle
      - light.pickle
      - light.sausage
      - light.hue_bar_left
      - light.hue_bar_right
      - light.moon_1
      - light.moon_2
      - light.moon_3
      - light.sun_1
      - light.sun_2
      - light.sun_3
      - light.sun_4
      - light.sun_5
  - platform: group
    unique_id: group_living_room_lights
    name: Living room lights
    entities:
      - light.avocado
      - light.luxo
      - light.pizza
      - light.hue_bar_left
      - light.hue_bar_right
      - light.moon_1
      - light.moon_2
      - light.moon_3
      - light.sun_1
      - light.sun_2
      - light.sun_3
      - light.sun_4
      - light.sun_5
  - platform: group
    unique_id: group_bedroom_lights
    name: Bedroom lights
    entities:
      - light.candle
      - light.sausage
      - light.pickle

# The filtering seems to be broken, it still adds million of items to HomeKit
# I'm not adding Home Assistant to HomeKit anymore
homekit:
  filter:
    include_entities: []

input_boolean:
  dogs_are_here:
    name: Dogs are with us now
    icon: mdi:dog
  someone_home:
    name: Someone is home
    icon: mdi:home-account

input_number:
  living_room_light_level:
    name: Living room light level
    icon: mdi:sun-clock
    min: 0
    max: 30000

group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include scripts.yaml
scene: !include scenes.yaml
