# Loads default set of integrations. Do not remove.
default_config:

# Light groups to control multiple lights together
light:
  # Living room ambient lights
  - platform: group
    unique_id: group_living_room_ambient_lights
    name: Living room ambient lights
    entities:
      - light.ember
      - light.sparkly_snake
  # All living room lights
  - platform: group
    unique_id: group_living_room_lights
    name: Living room lights
    entities:
      - light.ember
      - light.sparkly_snake
  # Office ambient lights
  - platform: group
    unique_id: group_office_ambient_lights
    name: Office ambient lights
    entities:
      - light.mushrump
      - light.sputnik
      - light.twix_1
      - light.twix_2
  # All office lights
  - platform: group
    unique_id: group_office_lights
    name: Office lights
    entities:
      - light.mushrump
      - light.sputnik
      - light.twix_1
      - light.twix_2
  # Bedroom ambient lights
  - platform: group
    unique_id: group_bedroom_ambient_lights
    name: Bedroom ambient lights
    entities:
      - light.sosiska
      - light.vader
  # Bathroom lights
  - platform: group
    unique_id: group_bathroom_lights
    name: Bathroom lights
    entities:
      - light.hippo_1
      - light.hippo_2

# Define boolean variables
input_boolean:
  # Someone is detected at home, set in automation/sensors.yaml
  someone_home:
    name: Someone is home
    icon: mdi:home-account

# Define integer variables
input_number:
  # Living room light level in lumens (lx), set in automation/sensors.yaml
  living_room_light_level:
    name: Living room light level
    icon: mdi:sun-clock
    min: 0
    max: 1000
  # Kitchen light level in lumens (lx), set in automation/sensors.yaml
  kitchen_light_level:
    name: Kitchen light level
    icon: mdi:sun-clock
    min: 0
    max: 1000
  # Bathroom light level in lumens (lx), set in automation/sensors.yaml
  bathroom_light_level:
    name: Bathroom light level
    icon: mdi:sun-clock
    min: 0
    max: 1000
  # Office light level in lumens (lx), set in automation/sensors.yaml
  office_light_level:
    name: Office light level
    icon: mdi:sun-clock
    min: 0
    max: 1000

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Load all automations from automations folder
automation: !include_dir_merge_list automations

# Load other scripts
script: !include scripts.yaml
scene: !include scenes.yaml
