- alias: "Wake up light (workdays)"
  id: wakeup_light_workdays
  trigger:
    - platform: time
      at: '06:00:00'
  condition:
    condition: and
    conditions:
     - condition: numeric_state
       entity_id: input_number.living_room_light_level
       below: 15000
     - condition: state
       entity_id: person.batman
       state: 'home'   
     - condition: time
       weekday:
         - mon
         - tue
         - wed
         - thu
         - fri
  action:
    - service: "light.turn_on"
      data:
        entity_id: light.candle
        brightness_pct: 15
        kelvin: 500
        transition: 300

- alias: "Wake up light (weekends)"
  id: wakeup_light_weekends
  trigger:
    - platform: time
      at: '07:20:00'
  condition:
    condition: and
    conditions:
     - condition: numeric_state
       entity_id: input_number.living_room_light_level
       below: 15000
     - condition: state
       entity_id: person.batman
       state: 'home'   
     - condition: time
       weekday:
         - sat
         - sun
  action:
    - service: "light.turn_on"
      data:
        entity_id: light.candle
        brightness_pct: 15
        kelvin: 500
        transition: 300

- alias: "Turn off wake up light"
  id: turn_off_wake_up_light
  trigger:
    - platform: time
      at: '09:00:00'
  action:
    - service: "light.turn_off"
      data:
        entity_id: light.group_galaxy
        transition: 60
