# Bathroom light switch

# Turn on to 100%, disabling the turn off automation
- alias: "Turn on bathroom lights to 100% on switch Hue button press"
  id: bathroom_light_switch_hue_on
  mode: single
  trigger:
    - trigger: state
      entity_id: event.bathroom_switch_button_4 # Hue button
      attribute: event_type
      to: initial_press
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.hippo
        brightness_pct: 100
        transition: 2

- alias: "Turn on bathroom lights on switch press"
  id: bathroom_light_switch_on
  mode: single
  trigger:
    - trigger: state
      entity_id: event.bathroom_switch_button_1 # On/off button
      attribute: event_type
      to: initial_press
  condition:
    - condition: state
      entity_id: light.hippo_1
      state: "off"
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.hippo
        brightness_pct: 95
        transition: 2
        
- alias: "Turn off bathroom lights on switch press"
  id: bathroom_light_switch_off
  mode: single
  trigger:
    - trigger: state
      entity_id: event.bathroom_switch_button_1 # On/off button
      attribute: event_type
      to: initial_press
  condition:
    - condition: state
      entity_id: light.hippo_1
      state: "on"
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.hippo
        transition: 2

- alias: "Brighten bathroom lights on switch button press"
  id: bathroom_light_switch_brighten
  mode: queued
  max: 10
  trigger:
    - trigger: state
      entity_id: event.bathroom_switch_button_2 # Brightness up button
      attribute: event_type
      to:
        - initial_press
        - repeat
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.hippo
        brightness_step_pct: 10
        transition: 0

- alias: "Dim bathroom lights on switch button press"
  id: bathroom_light_switch_dim
  mode: queued
  max: 10
  trigger:
    - trigger: state
      entity_id: event.bathroom_switch_button_3 # Brightness down button 
      attribute: event_type
      to:
        - initial_press
        - repeat
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.hippo
        brightness_step_pct: -10
        transition: 0

# Bathroom light: turn on when it's off

- alias: "Turn on bathroom light (day)"
  id: turn_on_bathroom_light_day
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_motion_sensor_motion
      from: "off"
      to: "on"
  condition:
    - condition: time
      after: "07:00:00"
      before: "17:00:00"
    - condition: numeric_state
      entity_id: input_number.bathroom_light_level
      below: 80 # lx
    - condition: state
      entity_id: light.hippo_1
      state: "off"
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.hippo
        brightness_pct: 95
        transition: 5

# Don’t check light level in the evening to avoid blackouts during shower, when
# the light level doesn’t get updated for some time, and hand-waving doesn’t
# work
- alias: "Turn on bathroom light (evening)"
  id: turn_on_bathroom_light_evening
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_motion_sensor_motion
      from: "off"
      to: "on"
  condition:
    - condition: time
      after: "17:00:00"
      before: "00:00:00"
    - condition: state
      entity_id: light.hippo_1
      state: "off"
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.hippo
        brightness_pct: 80
        transition: 5

- alias: "Turn on bathroom light (night)"
  id: turn_on_bathroom_light_night
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_motion_sensor_motion
      from: "off"
      to: "on"
  condition:
    - condition: time
      after: "00:00:00"
      before: "07:00:00"
    - condition: numeric_state
      entity_id: input_number.bathroom_light_level
      below: 80 # lx
    - condition: state
      entity_id: light.hippo_1
      state: "off"
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.hippo
        brightness_pct: 15
        transition: 5

# Bathroom light: turn off only when the level matches the level set by automation

- alias: "Turn off bathroom light"
  id: turn_off_bathroom_light
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_motion_sensor_motion
      to: "off"
      for:
        minutes: 10
  condition:
    - condition: numeric_state
      entity_id: light.hippo_1
      attribute: brightness
      below: 245 # 96%*255/100
  action:
    - service: "light.turn_off"
      data:
        entity_id:
          - light.hippo
        transition: 15
