- alias: "Turn on dining lights when it's dark"
  id: turn_on_dining_lights_when_dark
  trigger:
    platform: numeric_state
    entity_id: input_number.living_room_light_level
    below: 12000
  condition:
    - condition: state
      entity_id: group.family
      state: home
  action:
    - service: "light.turn_on"
      data:
        entity_id:
          - light.taquito
        brightness: 60
        kelvin: 3000
        transition: 180

- alias: "Turn off dining lights when it's light"
  id: turn_off_dining_lights_when_light
  trigger:
    platform: numeric_state
    entity_id: input_number.living_room_light_level
    above: 14000
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.taquito
        state: "on"
      - condition: numeric_state
        entity_id: light.taquito
        attribute: brightness
        below: 61
        above: 59
  action:
    service: "light.turn_off"
    data:
      entity_id: taquito
      transition: 180
