# Kitchen cooking light switch

- alias: "Turn on kitchen lights on switch press"
  id: kitchen_light_switch_on
  mode: single
  trigger:
    - trigger: device
      domain: hue
      type: initial_press
      subtype: 1 # On/off button
      device_id: 7c738080ffe740335dd27886fc39ba22
      unique_id: 60d3e8fa-6170-4acc-9d7b-cafb4eebea43
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: light.coco_1
        state: "off"
      - condition: numeric_state
        entity_id: light.coco_1
        attribute: brightness
        below: 128 # 50%*255/100
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.coco
        brightness_pct: 95
        transition: 2
        
- alias: "Turn off kitchen lights on switch press"
  id: kitchen_light_switch_off
  mode: single
  trigger:
    - trigger: device
      domain: hue
      type: initial_press
      subtype: 1 # On/off button
      device_id: 7c738080ffe740335dd27886fc39ba22
      unique_id: 60d3e8fa-6170-4acc-9d7b-cafb4eebea43
  condition:
    - condition: numeric_state
      entity_id: light.coco_1
      attribute: brightness
      above: 127 # 50%*255/100
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.coco
        transition: 2

- alias: "Brighten kitchen lights on switch button press"
  id: kitchen_light_switch_brighten
  mode: parallel
  max: 5
  trigger:
    - trigger: device
      domain: hue
      type: initial_press
      subtype: 2 # Brightness up button
      device_id: 7c738080ffe740335dd27886fc39ba22
      unique_id: 60d3e8fa-6170-4acc-9d7b-cafb4eebea43
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.coco
        brightness_step_pct: 5
        transition: 1

- alias: "Dim kitchen lights on switch button press"
  id: kitchen_light_switch_dim
  mode: parallel
  max: 5
  trigger:
    - trigger: device
      domain: hue
      type: initial_press
      subtype: 3 # Brightness down button
      device_id: 7c738080ffe740335dd27886fc39ba22
      unique_id: 60d3e8fa-6170-4acc-9d7b-cafb4eebea43
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.coco
        brightness_step_pct: -5
        transition: 1

# Turn on to 100%, disabling the turn off automation
- alias: "Turn on kitchen lights to 100% on switch Hue button press"
  id: kitchen_light_switch_hue_on
  mode: single
  trigger:
    - trigger: device
      domain: hue
      type: initial_press
      subtype: 4 # Hue button
      device_id: 7c738080ffe740335dd27886fc39ba22
      unique_id: 60d3e8fa-6170-4acc-9d7b-cafb4eebea43
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.coco
        brightness_pct: 100
        transition: 2

# Kitchen pilot light: turn on only when the group is off
- alias: "Turn on kitchen pilot light"
  id: turn_on_kitchen_pilot_light
  mode: single
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_motion_sensor_motion
      from: "off"
      to: "on"
    - platform: numeric_state
      entity_id: input_number.kitchen_light_level
      below: 60 # lx
  condition:
    - condition: state
      entity_id: binary_sensor.kitchen_motion_sensor_motion
      state: "on"
    - condition: numeric_state
      entity_id: input_number.kitchen_light_level
      below: 60 # lx
    - condition: state
      entity_id: light.coco_1
      state: "off"
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.coco_1
          - light.coco_4
          - light.coco_5
        brightness_pct: 20
        transition: 15

# Kitchen pilot light: turn off only when other lights in the group are also off
- alias: "Turn off kitchen pilot light"
  id: turn_off_kitchen_pilot_light
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.kitchen_motion_sensor_motion
      to: "off"
      for:
        minutes: 5
    - platform: numeric_state
      entity_id: input_number.kitchen_light_level
      below: 100 # lx
  condition:
    - condition: state
      entity_id: light.coco_2
      state: "off"
  action:
    - service: "light.turn_off"
      data:
        entity_id:
          - light.coco_1
          - light.coco_4
          - light.coco_5
        transition: 15

- alias: "Turn off kitchen island lights when Apple TV starts playing"
  id: turn_off_kitchen_island_light_tv_plays
  mode: single
  trigger:
    trigger: device
    device_id: bda48ebdbbda43616c71a7f9d9622b72
    domain: media_player
    entity_id: media_player.apple_tv
    type: playing
  action:
    - service: "light.turn_off"
      data:
        entity_id: 
          - light.cocodrilo
        transition: 60

- alias: "Turn off kitchen cooking lights when Apple TV starts playing"
  id: turn_off_kitchen_light_tv_plays
  mode: single
  trigger:
    trigger: device
    device_id: bda48ebdbbda43616c71a7f9d9622b72
    domain: media_player
    entity_id: media_player.apple_tv
    type: playing
  condition:
    condition: and
    conditions:
      # Only when it's not a pilot light
      - condition: numeric_state
        entity_id: light.coco_1
        attribute: brightness
        above: 76 # 30%*255/100
      # And the light is not locked
      - condition: numeric_state
        entity_id: light.coco_1
        attribute: brightness
        below: 245 # 96%*255/100
  action:
    - service: "light.turn_off"
      data:
        entity_id:
          - light.coco
        transition: 60

- alias: "Turn off all kitchen lights when nobody is there"
  id: turn_off_kitchen_lights_nobody
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.kitchen_motion_sensor_motion
      to: "off"
      for:
        minutes: 60
  action:
    - service: "light.turn_off"
      data:
        entity_id:
          - light.cocodrilo
          - light.coco
        transition: 15
