- alias: "Turn on ambient lights when it's dark"
  id: turn_on_ambient_light_when_dark
  trigger:
    - platform: numeric_state
      entity_id: input_number.living_room_light_level
      below: 12000
      for:
        minutes: 1
  condition:
    - condition: state
      entity_id: group.family
      state: home
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.avocado
          - light.luxo
          - light.group_twix
        brightness_pct: 25
        kelvin: 1000
        transition: 180
    - service: light.turn_on
      data:
        entity_id:
          - light.pizza
        brightness_pct: 10
        transition: 180

- alias: "Turn off ambient lights when it's light"
  id: turn_off_ambient_light_when_light
  trigger:
    - platform: numeric_state
      entity_id: input_number.living_room_light_level
      above: 13000
      for:
        minutes: 1
  action:
    service: "light.turn_off"
    data:
      entity_id: light.group_ambient_lights
      transition: 180

- alias: "Turn on ambient lights when somebody comes after sunset"
  id: turn_on_ambient_light_when_somebody_home_after_sunset
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.living_room_motion_sensor_motion
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: time
        before: "22:59:59"
        after: "09:00:00"
      - condition: numeric_state
        entity_id: input_number.living_room_light_level
        below: 12000
  action:
    service: "light.turn_on"
    data:
      entity_id: light.group_ambient_lights
      brightness_pct: 30
      kelvin: 1000
      transition: 15

- alias: Turn off ceiling lights when TV is on
  id: turn_off_ceiling_lights_when_tv_is_on
  mode: single
  trigger:
  - platform: device
    device_id: 0ff25cfec71f355cb5f25c0b7a0e61a9
    domain: media_player
    entity_id: media_player.monsterito
    type: turned_on
    for:
      seconds: 2
  condition: []
  action:
  - service: light.turn_off
    data:
      transition: 15
    target:
      entity_id:
        - light.group_sun
        - light.group_moon

- alias: "Turn on ambient lights when TV is on"
  id: turn_on_ambient_lights_when_tv_is_on
  trigger:
    platform: device
    device_id: 0ff25cfec71f355cb5f25c0b7a0e61a9
    domain: media_player
    entity_id: media_player.monsterito
    type: turned_on
    for:
      seconds: 2
  condition:
    condition: and
    conditions:
      - condition: time
        before: "23:00:00"
        after: "08:00:00"
      - condition: numeric_state
        entity_id: input_number.living_room_light_level
        below: 12000
  action:
    - service: "light.turn_on"
      data:
        entity_id: light.group_ambient_lights
        brightness_pct: 30
        kelvin: 1000
        transition: 30

- alias: "Turn off all lights when nobody is at home"
  id: turn_off_all_lghts_when_nobody_is_home
  trigger:
    platform: state
    entity_id: group.family
    from: home
    to: not_home
    for:
      minutes: 30
  action:
    service: "light.turn_off"
    entity_id: light.group_living_room_lights
