- alias: "Turn on ambient lights when somebody is in the room"
  id: turn_on_ambient_light_when_somebody_moves
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.living_room_motion_sensor_motion
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: time
        before: "22:59:59"
        after: "06:00:00"
      - condition: numeric_state
        entity_id: input_number.living_room_light_level
        below: 10000
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.group_twix
        brightness_pct: 25
        rgb_color: [245, 165, 0]
        transition: 180
    - service: light.turn_on
      data:
        entity_id:
          - light.pizza
        brightness_pct: 10
        transition: 180

- alias: "Turn on dining light when somebody is in the room"
  id: turn_on_dining_light_when_somebody_moves
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.living_room_motion_sensor_motion
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.taquito
        state: "off"
      - condition: time
        before: "22:59:59"
        after: "06:00:00"
      - condition: numeric_state
        entity_id: input_number.living_room_light_level
        below: 10000
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.taquito
        brightness_pct: 25
        rgb_color: [255, 165, 0]
        transition: 180

- alias: "Turn off ambient lights when it's light"
  id: turn_off_ambient_light_when_light
  trigger:
    - platform: numeric_state
      entity_id: input_number.living_room_light_level
      above: 11000
      for:
        minutes: 1
  action:
    service: "light.turn_off"
    data:
      entity_id: light.group_ambient_lights
      transition: 180

- alias: Turn off ceiling lights when TV is on
  id: turn_off_ceiling_lights_when_tv_is_on
  mode: single
  trigger:
  - platform: device
    device_id: 0ff25cfec71f355cb5f25c0b7a0e61a9
    domain: media_player
    entity_id: media_player.monsterito
    type: turned_on
    for:
      seconds: 2
  condition: []
  action:
  - service: light.turn_off
    data:
      transition: 15
    target:
      entity_id:
        - light.group_sun
        - light.group_moon

- alias: "Turn on ambient lights when TV is on"
  id: turn_on_ambient_lights_when_tv_is_on
  trigger:
    platform: device
    device_id: 0ff25cfec71f355cb5f25c0b7a0e61a9
    domain: media_player
    entity_id: media_player.monsterito
    type: turned_on
    for:
      seconds: 2
  condition:
    condition: and
    conditions:
      - condition: time
        before: "23:00:00"
        after: "08:00:00"
      - condition: numeric_state
        entity_id: input_number.living_room_light_level
        below: 10000
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.group_twix
          - light.taquito
        brightness_pct: 25
        rgb_color: [245, 165, 0]
        transition: 180
    - service: light.turn_on
      data:
        entity_id:
          - light.pizza
        brightness_pct: 10
        transition: 180

- alias: "Turn off all living room lights when nobody is there"
  id: turn_off_living_room_light_when_empty
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.living_room_motion_sensor_motion
      to: 'off'
      for:
        minutes: 60
  action:
    - service: "light.turn_off"
      data:
        entity_id: light.group_living_room_lights
        transition: 15
