- alias: "Turn on Sputnik when it's dark"
  id: turn_on_sputnik_when_dark
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.office_motion_sensor_motion
      from: 'off'
      to: 'on'
  condition:
    - condition: time
      after: "07:30:00"
      before: "21:30:00"
    - condition: numeric_state
      entity_id: input_number.office_light_level
      below: 10000
    - condition: state
      entity_id: light.sputnik
      state: "off"
  action:
    - service: light.turn_on
      data:
        entity_id: light.sputnik
        brightness_pct: 35
        kelvin: 1000
        transition: 30

- alias: "Turn on Sputnik when it's very dark"
  id: turn_on_sputnik_when_very_dark
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.office_motion_sensor_motion
      from: 'off'
      to: 'on'
  condition:
    - condition: time
      after: "07:30:00"
      before: "21:30:00"
    - condition: numeric_state
      entity_id: input_number.office_light_level
      below: 10000
    - condition: numeric_state
      entity_id: input_number.living_room_light_level
      below: 5000
    - condition: or
      conditions:
      - condition: state
        entity_id: light.sputnik
        state: "off"
      - condition: numeric_state
        entity_id: light.sputnik
        attribute: brightness
        above: 80 # ~35%
        below: 90
  action:
    - service: light.turn_on
      data:
        entity_id: light.sputnik
        brightness_pct: 70
        kelvin: 1000
        transition: 30

- alias: "Turn on Avocado when it's dark"
  id: turn_on_avocado_when_dark
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.office_motion_sensor_motion
      from: 'off'
      to: 'on'
  condition:
    - condition: time
      after: "07:30:00"
      before: "21:30:00"
    - condition: numeric_state
      entity_id: input_number.office_light_level
      below: 12000
    - condition: state
      entity_id: light.avocado
      state: "off"
  action:
    - service: light.turn_on
      data:
        entity_id: light.avocado
        brightness_pct: 50
        kelvin: 1000
        transition: 30

- alias: "Turn on Avocado when it's very dark"
  id: turn_on_avocado_when_very_dark
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.office_motion_sensor_motion
      from: 'off'
      to: 'on'
  condition:
    - condition: time
      after: "07:30:00"
      before: "21:30:00"
    - condition: numeric_state
      entity_id: input_number.office_light_level
      below: 10000
    - condition: numeric_state
      entity_id: input_number.living_room_light_level
      below: 7000
    - condition: or
      conditions:
      - condition: state
        entity_id: light.avocado
        state: "off"
      - condition: numeric_state
        entity_id: light.avocado
        attribute: brightness
        above: 125 # ~50%
        below: 135
  action:
    - service: light.turn_on
      data:
        entity_id: light.avocado
        brightness_pct: 80
        kelvin: 1000
        transition: 30

- alias: "Turn on Luxo when it's dark"
  id: turn_on_luxo_when_dark
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.office_motion_sensor_motion
      from: 'off'
      to: 'on'
  condition:
    - condition: time
      after: "07:30:00"
      before: "21:30:00"
    - condition: numeric_state
      entity_id: input_number.office_light_level
      below: 12000
    - condition: state
      entity_id: light.luxo
      state: "off"
  action:
    - service: light.turn_on
      data:
        entity_id: light.luxo
        brightness_pct: 50
        kelvin: 1000
        transition: 30

- alias: "Turn on Luxo when it's very dark"
  id: turn_on_luxo_when_very_dark
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.office_motion_sensor_motion
      from: 'off'
      to: 'on'
  condition:
    - condition: time
      after: "07:30:00"
      before: "21:30:00"
    - condition: numeric_state
      entity_id: input_number.office_light_level
      below: 10000
    - condition: numeric_state
      entity_id: input_number.living_room_light_level
      below: 7000
    - condition: or
      conditions:
      - condition: state
        entity_id: light.luxo
        state: "off"
      - condition: numeric_state
        entity_id: light.luxo
        attribute: brightness
        above: 125 # ~50%
        below: 135
  action:
    - service: light.turn_on
      data:
        entity_id: light.luxo
        brightness_pct: 80
        kelvin: 1000
        transition: 30

- alias: "Turn on Skillet when it's very dark"
  id: turn_on_skillet_when_very_dark
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.office_motion_sensor_motion
      from: 'off'
      to: 'on'
  condition:
    - condition: time
      after: "07:30:00"
      before: "21:30:00"
    - condition: numeric_state
      entity_id: input_number.office_light_level
      below: 10000
    - condition: numeric_state
      entity_id: input_number.living_room_light_level
      below: 7000
    - condition: state
      entity_id: light.skillet
      state: "off"
  action:
    - service: light.turn_on
      data:
        entity_id: light.skillet
        brightness_pct: 50
        kelvin: 1000
        transition: 30

- alias: "Turn on office night light"
  id: turn_on_office_night_light
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.office_motion_sensor_motion
      from: 'off'
      to: 'on'
  condition:
    - condition: time
      after: "21:31:00"
      before: "07:29:00"
  action:
    - service: light.turn_on
      data:
        entity_id: light.avocado
        brightness_pct: 15
        kelvin: 1000
        transition: 15

- alias: "Turn off office lights when it's light"
  id: turn_off_office_light_when_dark
  mode: single
  trigger:
    - platform: numeric_state
      entity_id:
        - input_number.office_light_level
      above: 11000
      for:
        minutes: 5
  action:
    - service: "light.turn_off"
      data:
        entity_id: light.group_office_ceiling_lights
        transition: 180

- alias: "Turn off office ambient lights when it's light"
  id: turn_off_office_ambient_light_when_dark
  mode: single
  trigger:
    - platform: numeric_state
      entity_id:
        - input_number.office_light_level
      above: 13000
      for:
        minutes: 15
  action:
    - service: "light.turn_off"
      data:
        entity_id: light.group_office_ambient_lights
        transition: 180

- alias: "Turn off working office lights when nobody is there"
  id: turn_off_work_office_light_when_empty
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.office_motion_sensor_motion
      to: 'off'
      for:
        minutes: 15
  action:
    - service: "light.turn_off"
      data:
        entity_id:
          - light.group_office_ceiling_lights
          - light.group_office_ambient_lights
        transition: 15

- alias: "Turn off all office lights when nobody is there"
  id: turn_off_office_light_when_empty
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.office_motion_sensor_motion
      to: 'off'
      for:
        hours: 3
  action:
    - service: "light.turn_off"
      data:
        entity_id: light.group_office_lights
        transition: 15

- alias: "Turn off office night light"
  id: turn_off_office_night_light
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.office_motion_sensor_motion
      to: 'off'
      for:
        minutes: 1
  condition:
    - condition: time
      after: "21:31:00"
      before: "07:29:00"
  action:
    - service: "light.turn_off"
      data:
        entity_id: light.avocado
        transition: 15
