- alias: "Turn on office lights when it's dark"
  id: turn_on_office_light_when_dark
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.office_motion_sensor_motion
      from: 'off'
      to: 'on'
  condition:
    - condition: time
      after: "07:30:00"
      before: "21:30:00"
    - condition: numeric_state
      entity_id: input_number.office_light_level
      below: 10000
  action:
    - service: light.turn_on
      data:
        entity_id: light.group_office_ceiling_lights
        brightness_pct: 35
        kelvin: 1000
        transition: 30

- alias: "Turn on office ambient lights when it's dark"
  id: turn_on_office_ambient_light_when_dark
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.office_motion_sensor_motion
      from: 'off'
      to: 'on'
  condition:
    - condition: time
      after: "07:30:00"
      before: "21:30:00"
    - condition: numeric_state
      entity_id: input_number.office_light_level
      below: 12000
  action:
    - service: light.turn_on
      data:
        entity_id: light.group_office_ambient_lights
        brightness_pct: 50
        kelvin: 1000
        transition: 30

- alias: "Turn on office night light"
  id: turn_on_office_night_light
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.office_motion_sensor_motion
      from: 'off'
      to: 'on'
  condition:
    - condition: time
      after: "21:31:00"
      before: "07:29:00"
  action:
    - service: light.turn_on
      data:
        entity_id: light.avocado
        brightness_pct: 10
        kelvin: 1000
        transition: 15

- alias: "Turn off office lights when it's light"
  id: turn_off_office_light_when_dark
  mode: single
  trigger:
    - platform: numeric_state
      entity_id:
        - input_number.office_light_level
      above: 11000
      for:
        minutes: 5
  action:
    - service: "light.turn_off"
      data:
        entity_id: light.group_office_ceiling_lights
        transition: 180

- alias: "Turn off office ambient lights when it's light"
  id: turn_off_office_ambient_light_when_dark
  mode: single
  trigger:
    - platform: numeric_state
      entity_id:
        - input_number.office_light_level
      above: 13000
      for:
        minutes: 15
  action:
    - service: "light.turn_off"
      data:
        entity_id: light.group_office_ambient_lights
        transition: 180

- alias: "Turn off all office lights when nobody is there"
  id: turn_off_office_light_when_empty
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.office_motion_sensor_motion
      to: 'off'
      for:
        minutes: 15
  action:
    - service: "light.turn_off"
      data:
        entity_id: light.group_office_lights
        transition: 15

- alias: "Turn off office night light"
  id: turn_off_office_night_light
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.office_motion_sensor_motion
      to: 'off'
      for:
        minutes: 1
  condition:
    - condition: time
      after: "21:31:00"
      before: "07:29:00"
  action:
    - service: "light.turn_off"
      data:
        entity_id: light.avocado
        transition: 15
