- alias: "Save the current light level in Living room"
  id: save_current_light_level_living_room
  mode: single
  trigger:
  - platform: time_pattern
    seconds: /15
  action:
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id: sensor.living_room_motion_sensor_illuminance
  - service: input_number.set_value
    target:
      entity_id: input_number.living_room_light_level
    data:
      value: "{{ state_attr('sensor.living_room_motion_sensor_illuminance', 'light_level') | int }}"


- alias: Turn on presense
  id: turn_on_presense
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.living_room_motion_sensor_motion
      from: 'off'
      to: 'on'
    - platform: state
      entity_id:
        - binary_sensor.bathroom_motion_sensor_motion
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: group.family
      from: not_home
      to: home
  condition: []
  action:
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id: input_boolean.someone_home

- alias: Turn off presense
  id: turn_off_presense
  mode: single
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.living_room_motion_sensor_motion
      from: 'on'
      to: 'off'
      for:
        minutes: 61
    - platform: state
      entity_id:
        - binary_sensor.bathroom_motion_sensor_motion
      from: 'on'
      to: 'off'
      for:
        minutes: 61
    - platform: state
      entity_id: group.family
      from: home
      to: not_home
      for:
        minutes: 31
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id:
          - binary_sensor.living_room_motion_sensor_motion
        state: 'off'
        for:
          minutes: 60
      - condition: state
        entity_id:
          - binary_sensor.bathroom_motion_sensor_motion
        state: 'off'
        for:
          minutes: 60
      - condition: state
        entity_id: group.family
        state: not_home
        for:
          minutes: 30
  action:
    - service: input_boolean.turn_off
      data: {}
      target:
        entity_id: input_boolean.someone_home
